FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-dev \
    libpcap-dev \
    tcpdump \
    iputils-ping \
    net-tools \
    iptables \
    dsniff \
    nmap \
    nano \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install scapy python-libpcap

WORKDIR /app

CMD ["bash"]